<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net472</TargetFrameworks>
    <RootNamespace>NLog.Targets.Syslog</RootNamespace>
    <OutputType>Library</OutputType>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>false</ContinuousIntegrationBuild>

    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>


    <Product>XDev.NLog.Targets.Syslog</Product>
    <AssemblyTitle>NLog Syslog target</AssemblyTitle>
    <AssemblyName>NLog.Targets.Syslog</AssemblyName>
    <AssemblyVersion>0.0.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
    <InformationalVersion>0.1.0-alpha.1+commitHash</InformationalVersion>
    <NeutralLanguage>en</NeutralLanguage>

    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

    <Company>XDev</Company>
    <Authors>XDev</Authors>
    <PackageId>XDev.NLog.Targets.Syslog</PackageId>
    <Title>XDev.NLog.Targets.Syslog</Title>
    <Description>
      Custom target for NLog to send logging messages to a Syslog server.
      Forked from https://github.com/luigiberrettini/NLog.Targets.Syslog and namespace-compatible.
    </Description>
    <PackageTags>NLog Syslog Log Logging Maui</PackageTags>
    <Version>0.1.0-alpha.1</Version>
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/jasells/NLog.Targets.Syslog</PackageProjectUrl>
    <PackageIcon>NLog.Targets.Syslog.png</PackageIcon>
    <RepositoryUrl>https://github.com/jasells/NLog.Targets.Syslog</RepositoryUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageReleaseNotes>
      Added support for NLog v6 by replacing SdIdConfig with SimpleLayout
    </PackageReleaseNotes>
    <RepositoryType>Git</RepositoryType>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <DebugType>portable</DebugType>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <!--<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>-->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
    <PackageReference Include="NLog" Version="5.0.0" />
    <PackageReference Include="Polly.Contrib.WaitAndRetry" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE" Pack="True" PackagePath="" />
    <None Include="..\NLog.Targets.Syslog.png" Pack="true" PackagePath="" />
    <None Include="..\..\Docs\README.md" Pack="true" PackagePath="" />
    <!--<None Include="NLog.Targets.Syslog.snk" />-->
  </ItemGroup>
</Project>